export default {
  SET_SELECTED_SOURCE_TAB: "SET_SELECTED_SOURCE_TAB",
  SET_SELECTED_CHANNEL_TAB: "SET_SELECTED_CHANNEL_TAB",
  SET_SELECTED_WHATSAPP_CHANNEL_TAB: "SET_SELECTED_WHATSAPP_CHANNEL_TAB",
  SET_SELECTED_SUBMODULE_TAB: "SET_SELECTED_SUBMODULE_TAB",
  SET_SUBHEADER_TAB: "SET_SUBHEADER_TAB",
};
