const actionTypes = {
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SUMMARY_GET_API_REQUEST: "SUMMARY_GET_API_REQUEST",
  SUMMARY_GET_API_SUCCESS: "SUMMARY_GET_API_SUCCESS",
  SUMMARY_GET_API_FAILURE: "SUMMARY_GET_API_FAILURE",
  TRANSCRIPT_GET_API_REQUEST: "TRANSCRIPT_GET_API_REQUEST",
  TRANSCRIPT_GET_API_SUCCESS: "TRANSCRIPT_GET_API_SUCCESS",
  TRANSCRIPT_GET_API_FAILURE: "TRANSCRIPT_GET_API_FAILURE",
  FEEDBACK_POST_API_REQUEST: "FEEDBACK_POST_API_REQUEST",
  FEEDBACK_POST_API_SUCCESS: "FEEDBACK_POST_API_SUCCESS",
  FEEDBACK_POST_API_FAILURE: "FEEDBACK_POST_API_FAILURE",
  FEEDBACK_HISTORY_API_REQUEST: "FEEDBACK_HISTORY_API_REQUEST",
  FEEDBACK_HISTORY_API_SUCCESS: "FEEDBACK_HISTORY_API_SUCCESS",
  FEEDBACK_HISTORY_API_FAILURE: "FEEDBACK_HISTORY_API_FAILURE",
  REPORT_ISSUE_API_REQUEST: "REPORT_ISSUE_API_REQUEST",
  SET_FEEDBACK_HISTORY_TABLE_DATA: "SET_FEEDBACK_HISTORY_TABLE_DATA",
  SET_FEEDBACK_CALENDER_DATA: "SET_FEEDBACK_CALENDER_DATA",
  PORTAL_TRANSCRIPT_DOWNLOAD_CSV: "PORTAL_TRANSCRIPT_DOWNLOAD_CSV",
  FEEDBACK_HISTORY_DOWNLOAD_CSV: "FEEDBACK_HISTORY_DOWNLOAD_CSV",
  REPORT_ISSUE_DOWNLOAD_CSV: "REPORT_ISSUE_DOWNLOAD_CSV",
};

export default actionTypes;
