export default   {
  ADD_CUSTOMER: "ADD_CUSTOMER",
  DELETE_CUSTOMER: "DELETE_CUSTOMER",
  ADD_FETCHED_CUSTOMERS: "ADD_FETCHED_CUSTOMERS",
  SET_DISABLE_BUTTON: "SET_DISABLE_BUTTON",
  UPDATE_CUSTOMER_DATA: "UPDATE_CUSTOMER_DATA",
  PUSH_DATA_API:"PUSH_DATA_API"
};

