const AllClientActionTypes = {
  SET_ALL_CLIENT: "SET_ALL_CLIENT",
  SET_CURRENT_CLIENT_SAGA: "SET_CURRENT_CLIENT_SAGA",
  SET_CURRENT_CLIENT: "SET_CURRENT_CLIENT",
  GET_ALL_CLIENT: "GET_ALL_CLIENT",
  SET_LOADING: "SET_LOADING",
};

export default AllClientActionTypes;
