export const campaignTestingConfig = (userName) => {
  let config = {
  
    Testhealth: {
      flow: [],
      language: [],
    },
    teleXYZ: {
      flow: [],
      language: [],
    },
    "BadaBusiness Testing": {
      flow: [],
      language: [],
    },
    TestingBFSI: {
      flow: [],
      language: [],
    },
    testing1: {
      flow: [],
      language: [],
    },
    retest: {
      flow: [],
      language: [],
    },
    Cleartouch: {
      flow: ["Pre-Due"],
      language: ["English"],
    },
    TestSSR: {
      flow: [],
      language: [],
    },
    "Dsa Testing": {
      flow: ["lead_gen"],
      language: ["English", "Hindi"],
    },
    "LnT Testing": {
      flow: [],
      language: [],
    },
    "Fincare Testing": {
      flow: [],
      language: [],
    },
    "Chqbook Testing": {
      flow: ["post_due_30_plus", "post_due_8_15"],
      language: ["English", "Hindi"],
    },
    "Pravid Demo": {
      flow: ["Post Due", "Pre Due"],
      language: ["Hindi"],
    },
    "prod testing": {
      flow: [],
      language: [],
    },
    MG_ANNOTATOR: {
      flow: [],
      language: [],
    },
    "Probus Insurance Testing": {
      flow: ["voice_artist"],
      language: ["English", "Hindi"],
      telephonyData: {
        "loanAccountDetails.emiAmount": "9000",
        "loanAccountDetails.emiDueDate": "17-09-2022",
        "primaryInfo.flow": "voice_artist",
        "primaryInfo.language": "english",
        "loanAccountDetails.noOfLoans": "2",
        clientName: "Probus Testing",
        callId: "123455",
        "loanAccountDetails.loanId": "23045278",
      },
    },
    trsting45: {
      flow: [],
      language: [],
    },
    Testing2: {
      flow: [],
      language: [],
    },
    ok: {
      flow: [],
      language: [],
    },
    "Tune Talk": {
      flow: [],
      language: ["English"],
    },
    "Kreditbee Testing": {
      flow: ["pre_emi", "ptp_sdf", "due_date", "dpd_minus_2", "dpd_minus_1"],
      language: ["Hindi", "Kannada", "Malayalam", "Tamil", "Telugu", "English"],
      telephonyData: {
        "loanAccountDetails.emiAmount": "9000",
        "loanAccountDetails.emiDueDate": "17-09-2022",
        "primaryInfo.flow": "due_date",
        "primaryInfo.language": "english",
        clientName: "Kreditbee Debt",
        callId: "123455",
        bargingCall: "True",
        "loanAccountDetails.loanId": "23045278",
      },
    },
    fdfgfg: {
      flow: [],
      language: [],
    },
    Manappuram: {
      flow: ["Pre Due", "pre_emi"],
      language: ["Hindi", "Kannada", "Malayalam", "Tamil", "Telugu"],
    },
    Chqbook: {
      flow: [],
      language: [],
    },
    Kreditbee: {
      flow: [],
      language: [],
    },
    jlhjkl: {
      flow: [],
      language: [],
    },
    newAbhiAcc: {
      flow: [],
      language: [],
    },
    Payme: {
      flow: [],
      language: [],
    },
    "saarthi-test": {
      flow: [],
      language: [],
    },
    testing5: {
      flow: [],
      language: [],
    },
    "Bajaj Finserv Testing": {
      flow: [
        "dpd_1_4_executive",
        "dpd_1_4_touchfree",
        "nil_pos",
        "post_due_0_7",
        "nilpos_waiver_bad",
        "nilpos_waiver_good",
      ],
      language: [
        "English",
        "Hindi",
        "Malayalam",
        "Marathi",
        "Tamil",
        "Telugu",
        "Gujarati",
      ],
      telephonyData: {
        "contactInfo.primary": "8884974479",
        "loanAccountDetails.emiAmount": "5089",
        "loanAccountDetails.emiDueDate": "10-09-2022",
        "primaryInfo.firstName": "Kundan",
        "primaryInfo.flow": "nil_pos",
        "primaryInfo.language": "english",
        clientName: "Bajaj Finserv Testing",
        callId: "123455",
        bargingCall: "True",
        "loanAccountDetails.loanId": "12334",
        percentage_1: "5",
        percentage_2: "10",
      },
    },
    testing56: {
      flow: [],
      language: [],
    },
    Navi: {
      flow: [],
      language: [],
    },
    "Ola Money": {
      flow: [],
      language: [],
    },
    Homefirst: {
      flow: [],
      language: [],
    },
    "Ola Money Testing": {
      flow: [],
      language: [],
    },
    Saarthi: {
      flow: [
        "DPD 1-7",
        "DPD 15+",
        "Post Bounce DPD 1-7",
        "Post Bounce DPD 8-15",
        "Post Bounce DPD 8-20",
        "Post Bounce dpd7",
        "Pre Due",
        "Pre Due Reminder",
        "Pre-Due",
        "dpd_minus_1",
        "dpd_minus_2",
        "due_date",
        "nil_pos",
        "post-due",
        "post_due_0_7",
        "post_due_1_7",
        "pre-due",
        "pre_emi_S_h_g",
        "pre_emi_S_lca",
        "pre_emi_S_lcb",
        "pre_emi_X_h_g",
        "pre_emi_X_lca",
      ],
      language: [
        "English",
        "Gujarati",
        "Hindi",
        "Kannada",
        "Malayalam",
        "Marathi",
        "Tamil",
        "Telugu",
      ],
    },
    "Manappuram Testing": {
      flow: [
        "pre_emi",
        "post_emi_dpd7",
        "post_emi_dpd15",
        "post_emi_dpd15+",
        "cv",
        "npa",
      ],
      language: [
        "Bangla",
        "Hindi",
        "Kannada",
        "Malayalam",
        "Odia",
        "Tamil",
        "Telugu",
      ],
      telephonyData: {
        "loanAccountDetails.emiAmount": "9000",
        "loanAccountDetails.emiDueDate": "17-09-2022",
        "primaryInfo.flow": "pre_emi",
        "primaryInfo.language": "hindi",
        "loanAccountDetails.noOfLoans": "2",
        callId: "123455",
        "loanAccountDetails.loanId": "23045278",
      },
    },
    abhusd: {
      flow: [],
      language: [],
    },
    testing: {
      flow: [],
      language: [],
    },
    "flow-test": {
      flow: [],
      language: [],
    },
    "AU Finance Testing": {
      flow: ["Pre Due", "post_due_0_7"],
      language: ["English", "Kannada"],
    },
    "Sriram Testing": {
      flow: ["pre_emi", "post_due_0_7", "PTP-Reminder"],
      language: [
        "Bangla",
        "Gujarati",
        "Hindi",
        "English",
        "Kannada",
        "Malayalam",
        "Marathi",
        "Punjabi",
        "Tamil",
        "Telugu",
      ],
      telephonyData: {
        "loanAccountDetails.emiAmount": "9000",
        "loanAccountDetails.emiDueDate": "17-09-2022",
        "primaryInfo.flow": "post_due_0_7",
        "primaryInfo.language": "english",
        "loanAccountDetails.noOfLoans": "2",
        clientName: "Sriram Testing",
        callId: "123455",
        "loanAccountDetails.loanId": "23045278",
      },
    },
    "Tata Cliq Testing": {
      flow: [],
      language: ["English"],
    },
    saarthiHealthCare: {
      flow: [],
      language: [],
    },
    "Maia Testing": {
      flow: [
        "Pre_Due",
        "Due_Date",
        "DPD_1-3",
        "DPD_4-7",
        "DPD_8-15",
        "DPD_16-30",
      ],
      language: ["Hindi", "English"],
      telephonyData: {
        "loanAccountDetails.emiAmount": "80250",
        "loanAccountDetails.emiDueDate": "02-10-2022",
        "email.primary": "r18r18@gmail.com",
        "loanAccountDetails.loanId": "test1",
        "loanAccountDetails.noOfLoans": "4",
        "primaryInfo.age": 25,
        "primaryInfo.gender": "M",
        "primaryInfo.geographicLocation": "bangalore",
        "primaryInfo.region": "Urban",
        "primaryInfo.collared": "Blue",
        "loanAccountDetails.totalLoanAmount": "10000",
        "loanAccountDetails.interestRate": "4",
        "loanAccountDetails.principalAmount": "25000",
        "loanAccountDetails.lateFee": "100",
        "loanAccountDetails.loanApplicationDate": "02-06-2022",
        "loanAccountDetails.loanEndingDate": "02-10-2022",
        "loanAccountDetails.loanAmountRemaining": "40000",
        "loanAccountDetails.loanTenureLeft": "50000",
        "behaviourDetails.typology": "WAOR",
        callId: "12345",
        bargingCall: "True",
        "behaviourDetails.callDisposition": "normal",
        "loanAccountDetails.loanTenureLeft": "5",
        "loanAccountDetails.noofemi": "2",
        "loanAccountDetails.noOfLoanTaken": "4",
        "loanAccountDetails.noOfEmiPaid": "2",
        "loanAccountDetails.totalLoanAmount": "4566",
        "loanAccountDetails.interestRate": "4",
        "loanAccountDetails.principalAmount": "4567",
      },
    },
    "Demo Testing" : {
      flow: [
        "Pre_Due",
        "Due_Date",
        "DPD_1-3",
        "DPD_4-7",
        "DPD_8-15",
        "DPD_16-30",
      ],
      language: ["Hindi", "English"],
      telephonyData: {
        "loanAccountDetails.emiAmount": "80250",
        "loanAccountDetails.emiDueDate": "02-10-2022",
        "email.primary": "r18r18@gmail.com",
        "loanAccountDetails.loanId": "test1",
        "loanAccountDetails.noOfLoans": "4",
        "primaryInfo.age": 25,
        "primaryInfo.gender": "M",
        "primaryInfo.geographicLocation": "bangalore",
        "primaryInfo.region": "Urban",
        "primaryInfo.collared": "Blue",
        "loanAccountDetails.totalLoanAmount": "10000",
        "loanAccountDetails.interestRate": "4",
        "loanAccountDetails.principalAmount": "25000",
        "loanAccountDetails.lateFee": "100",
        "loanAccountDetails.loanApplicationDate": "02-06-2022",
        "loanAccountDetails.loanEndingDate": "02-10-2022",
        "loanAccountDetails.loanAmountRemaining": "40000",
        "loanAccountDetails.loanTenureLeft": "50000",
        "behaviourDetails.typology": "WAOR",
        callId: "12345",
        bargingCall: "True",
        "behaviourDetails.callDisposition": "normal",
        "loanAccountDetails.loanTenureLeft": "5",
        "loanAccountDetails.noofemi": "2",
        "loanAccountDetails.noOfLoanTaken": "4",
        "loanAccountDetails.noOfEmiPaid": "2",
        "loanAccountDetails.totalLoanAmount": "4566",
        "loanAccountDetails.interestRate": "4",
        "loanAccountDetails.principalAmount": "4567",
      },
    },
    "Demo" : {
      flow: [
        "Pre_Due",
        "Due_Date",
        "DPD_1-3",
        "DPD_4-7",
        "DPD_8-15",
        "DPD_16-30",
      ],
      language: ["Hindi", "English"],
      telephonyData: {
        "loanAccountDetails.emiAmount": "80250",
        "loanAccountDetails.emiDueDate": "02-10-2022",
        "email.primary": "r18r18@gmail.com",
        "loanAccountDetails.loanId": "test1",
        "loanAccountDetails.noOfLoans": "4",
        "primaryInfo.age": 25,
        "primaryInfo.gender": "M",
        "primaryInfo.geographicLocation": "bangalore",
        "primaryInfo.region": "Urban",
        "primaryInfo.collared": "Blue",
        "loanAccountDetails.totalLoanAmount": "10000",
        "loanAccountDetails.interestRate": "4",
        "loanAccountDetails.principalAmount": "25000",
        "loanAccountDetails.lateFee": "100",
        "loanAccountDetails.loanApplicationDate": "02-06-2022",
        "loanAccountDetails.loanEndingDate": "02-10-2022",
        "loanAccountDetails.loanAmountRemaining": "40000",
        "loanAccountDetails.loanTenureLeft": "50000",
        "behaviourDetails.typology": "WAOR",
        callId: "12345",
        bargingCall: "True",
        "behaviourDetails.callDisposition": "normal",
        "loanAccountDetails.loanTenureLeft": "5",
        "loanAccountDetails.noofemi": "2",
        "loanAccountDetails.noOfLoanTaken": "4",
        "loanAccountDetails.noOfEmiPaid": "2",
        "loanAccountDetails.totalLoanAmount": "4566",
        "loanAccountDetails.interestRate": "4",
        "loanAccountDetails.principalAmount": "4567",
      },
    },
    myHos: {
      flow: [],
      language: [],
    },
    "Cred Testing": {
      flow: [
        "post bounce dpd 1-7",
        "post bounce dpd 8-20",
        "post bounce dpd 1-7_x",
        "post bounce dpd 8-20_x",
        "pre_emi_regular",
        "pre_emi_default",
        "ptp_breach_soft",
        "ptp_breach_hard",
        "ptp_sdf",
      ],
      language: ["English", "Hindi", "Kannada", "Tamil", "Telugu"],
      telephonyData: {
        "loanAccountDetails.emiAmount": "9000",
        "loanAccountDetails.emiDueDate": "17-09-2022",
        "primaryInfo.firstName": "Kundan",
        "primaryInfo.flow": "pre_emi_default",
        "primaryInfo.language": "english",
        "loanAccountDetails.noOfLoans": "2",
        clientName: "Cred Testing",
        callId: "123455",
        bargingCall: "True",
        "loanAccountDetails.loanId": "23045278",
      },
    },
    "Saarthi Demo": {
      flow: [
        "DPD 1-7",
        "DPD 15+",
        "DPD 30+",
        "DPD 8-15",
        "Pre Due",
        "Pre-Due",
        "Saarthi Demo",
        "dpd_8_15",
      ],
      language: ["English", "Hindi", "Telugu"],
    },
    "Wheelseye Testing": {
      flow: [],
      language: [],
    },
    Udaan: {
      flow: [],
      language: [],
    },
    "Udaan Testing": {
      flow: [],
      language: [],
    },
    "ABC Hospital": {
      flow: [],
      language: [],
    },
    "Gouri Telecom": {
      flow: [],
      language: [],
    },
    abhis: {
      flow: [],
      language: [],
    },
    ITC: {
      flow: [],
      language: [],
    },
    "ITC Testing": {
      flow: [],
      language: [],
    },
    "staging testing": {
      flow: [],
      language: [],
    },
    abhiTest89: {
      flow: [],
      language: [],
    },
    Avail: {
      flow: [
        "Post Bounce DPD 1-7",
        "Post Bounce DPD 16-30",
        "Post Bounce DPD 30+",
        "Post Bounce DPD 8-15",
        "Pre Due Reminder",
        "pre due reminder",
      ],
      language: ["English", "Hindi", "Kannada", "Tamil", "Telugu"],
    },
    "Account-0023": {
      flow: [],
      language: [],
    },
    "HDFC Testing": {
      flow: ["Pre_due", "Post_due"],
      language: ["English", "Hindi"],
      telephonyData: {
        "loanAccountDetails.emiAmount": "5000",
        "loanAccountDetails.emiDueDate": "28-03-2022",
        "email.primary": "qewreeds@gmail.com",
        callId: "62dd199efafb0f5f0e527eef",
        bargingCall: "True",
        "loanAccountDetails.loanId": "hdbwhj",
        "loanAccountDetails.nach": "yes",
        "primaryInfo.region": "delhi",
        "behaviourDetails.currentPTPDays": "20",
        "loanAccountDetails.noOfLoans": 2,
      },
    },
    Dsa: {
      flow: [],
      language: [],
    },
    "Kreditbee-PayU": {
      flow: [],
      language: [],
    },
    "nithin test": {
      flow: [],
      language: [],
    },
    saarthiTelecom: {
      flow: [],
      language: [],
    },
    myTel: {
      flow: [],
      language: [],
    },
    "Tune Talk Testing": {
      flow: [],
      language: ["English"],
    },
    "LendingKart Testing": {
      flow: ["post_due_0_7", "pre_emi_lk"],
      language: ["English"],
      telephonyData: {
        "loanAccountDetails.emiAmount": "80250",
        "loanAccountDetails.emiDueDate": "02-08-2022",
        "email.primary": "r18r18@gmail.com",
        "loanAccountDetails.loanId": "test1",
      },
    },
    Indostar: {
      flow: ["Pre Due"],
      language: ["Hindi", "Kannada", "Marathi", "Tamil", "Telugu"],
    },
    "GAMUT ANALYTICS PRIVATE LIMITED": {
      flow: [],
      language: [],
    },
    myHospital: {
      flow: [],
      language: [],
    },
    helloTest: {
      flow: [],
      language: [],
    },
    Ceat: {
      flow: ["Warranty Flow"],
      language: ["Hindi"],
    },
    InternalTesting: {
      flow: [
        "Pre-Due",
        "post-due",
        "post_due_0_7",
        "pre-due",
        "pre-flow",
        "pre_emi",
        "Pre Due",
      ],
      language: ["English", "Hindi"],
    },
    "DPD Zero": {
      flow: [],
      language: [],
    },
    "dfghjkl;kjhgfghjkl;kjhgfghjkljhgfhjkilikjhgfhjkjhgfghukyhgfdgtyuiytrdtyuiytretyuiytrtyutrdfrtyugfhjhffhdfhdsfhgffhgdfghfhgdghfhgfdshgfghghdsfghghdsfghhgfsdghfdgsfhfghdshfgfghsdfghfghhgfsdfghdshgfhgfghfsdhgdhgfdshgdshghg":
      {
        flow: [],
        language: [],
      },
    swatiAndSonsHospitals: {
      flow: [],
      language: [],
    },
    "Navi Testing": {
      flow: [],
      language: [],
    },
    test66: {
      flow: [],
      language: [],
    },
    BadaBusiness: {
      flow: [],
      language: [],
    },
    "Aadhar Housing Testing": {
      flow: ["aadhar_pre_due"],

      language: ["English", "Hindi", "Tamil", "Malayalam"],
      telephonyData: {
        "loanAccountDetails.emiAmount": "9000",
        "loanAccountDetails.emiDueDate": "17-09-2022",
        "primaryInfo.firstName": "Kundan",
        "primaryInfo.flow": "due_date",
        "primaryInfo.language": "english",
        clientName: "Aadhar Housing Testing",
        callId: "123455",
        bargingCall: "True",
        "loanAccountDetails.loanId": "23045278",
        customerInfo: {
          others: {
            linkStatus: "No",
          },
        },
      },
    },
    allflowTest: {
      flow: [],
      language: [],
    },
    "Capri Global Testing": {
      flow: [
        "Pre_due_ML_call_disconnected",
        "Pre_due_ML_default",
        "Pre_due_ML_default_x",
        "Pre_due_ML_follow_up",
        "Pre_due_ML_not_connected",
        "Pre_due_ML_regular",
        "Pre_due_SL_call_disconnected",
        "Pre_due_SL_default",
        "Pre_due_SL_default_x",
        "Pre_due_SL_follow_up",
        "Pre_due_SL_not_connected",
        "Pre_due_SL_regular",
      ],
      language: ["Gujarati", "Hindi"],
      telephonyData: {
        "loanAccountDetails.emiAmount": "5000",
        "loanAccountDetails.emiDueDate": "28-03-2022",
        "email.primary": "qewreeds@gmail.com",
        callId: "62dd199efafb0f5f0e527eef",
        bargingCall: "True",
        "loanAccountDetails.loanId": "hdbwhj",
        "loanAccountDetails.nach": "no",
        "primaryInfo.region": "delhi",
        "behaviourDetails.currentPTPDays": "2",
        "loanAccountDetails.noOfLoans": 2,
      },
    },
    "Capri Azure Testing": {
      flow: [
        "Pre_due_ML_call_disconnected",
        "Pre_due_ML_default",
        "Pre_due_ML_default_x",
        "Pre_due_ML_follow_up",
        "Pre_due_ML_not_connected",
        "Pre_due_ML_regular",
        "Pre_due_SL_call_disconnected",
        "Pre_due_SL_default",
        "Pre_due_SL_default_x",
        "Pre_due_SL_follow_up",
        "Pre_due_SL_not_connected",
        "Pre_due_SL_regular",
      ],
      language: ["Gujarati", "Hindi"],
      telephonyData: {
        "loanAccountDetails.emiAmount": "5000",
        "loanAccountDetails.emiDueDate": "28-03-2022",
        "primaryInfo.flow": "Pre_due_SL_default",
        "primaryInfo.language": "hindi",
        "email.primary": "qewreeds@gmail.com",
        clientName: "Capri Azure Testing",
        callId: "62dd199efafb0f5f0e527eef",
        bargingCall: "True",
        "loanAccountDetails.loanId": "hdbwhj",
        "loanAccountDetails.nach": "yes",
        "primaryInfo.region": "delhi",
        "behaviourDetails.currentPTPDays": "20",
        "loanAccountDetails.noOfLoans": 2,
      },
    },
    TESTING_HEALTH: {
      flow: [],
      language: [],
    },
    "Maha Bussines": {
      flow: [],
      language: [],
    },
    "test account": {
      flow: [],
      language: [],
    },
    testPQR: {
      flow: [],
      language: [],
    },
    gndvmbfdm: {
      flow: [],
      language: [],
    },
    "First Account": {
      flow: ["post_due_0_7"],
      language: ["Hindi"],
    },
    testABC: {
      flow: [],
      language: [],
    },
    "Indostar Testing": {
      flow: ["pre_emi", "post_emi"],
      language: ["Hindi", "Kannada", "Marathi", "Tamil", "Telugu", "English"],
      telephonyData: {
        "loanAccountDetails.emiAmount": "9000",
        "loanAccountDetails.emiDueDate": "17-09-2022",
        "primaryInfo.firstName": "Kundan",
        "primaryInfo.flow": "pre_emi",
        "primaryInfo.language": "hindi",
        clientName: "Indostar Testing",
        callId: "123455",
        bargingCall: "True",
        "loanAccountDetails.loanId": "23045278",
        customerInfo: {
          others: {
            linkStatus: "NO",
          },
        },
      },
    },
    test65: {
      flow: [],
      language: [],
    },
    "Abhi Telecom": {
      flow: [],
      language: [],
    },
    Test: {
      flow: [],
      language: [],
    },
    NewTestAccount: {
      flow: [],
      language: [],
    },
    abhiTest02: {
      flow: [],
      language: [],
    },
    "Lendingkart Technologies Testing": {
      flow: ["post_due_0_7"],
      language: ["English"],
    },
    testing10: {
      flow: [],
      language: [],
    },
    Fedfina: {
      flow: [],
      language: [],
    },
    "PayMe Testing": {
      flow: [],
      language: [],
    },
    GTesting: {
      flow: [],
      language: [],
    },
    "Bajaj Finserv Counselling Testing": {
      flow: ["FEMI_1", "Non_FEMI_1", "OIT_1", "Non_FEMI_2", "OIT_2", "FEMI_2"],
      language: ["English", "Hindi", "Malayalam", "Marathi", "Tamil", "Telugu"],
      telephonyData: {
        "loanAccountDetails.emiAmount": "75252",
        "loanAccountDetails.emiDueDate": "28-03-2022",
        "email.primary": "qewreeds@gmail.com",
        bargingCall: "True",
        "loanAccountDetails.loanId": "12334",
        percentage_1: "5",
        percentage_2: "10",
        callId: "62e26e45bfc1f519ab81a3ea",
        bargingCall: "True",
        customerInfo: {
          loanAccountDetails: {
            bankAccountNumber: "1234567",
            bankName: "state bank of india",
          },
        },
      },
    },
    Manya: {
      flow: [],
      language: [],
    },
    Sriram: {
      flow: ["post_due_0_7"],
      language: [
        "Bangla",
        "English",
        "Hindi",
        "Kannada",
        "Marathi",
        "Tamil",
        "Telugu",
      ],
    },
    "Fedfina Testing": {
      flow: [],
      language: [],
    },
    asjgyuqssgyuc: {
      flow: [],
      language: [],
    },
    "DPD Zero Testing": {
      flow: [],
      language: [],
    },
    "new telecom account": {
      flow: [],
      language: [],
    },
    RTesting: {
      flow: [],
      language: [],
    },
    STesting: {
      flow: [],
      language: [],
    },
    "testnew Account": {
      flow: [],
      language: [],
    },
    "Whatsapp Marketingl": {
      flow: [],
      language: [],
    },
    abhiTranscript: {
      flow: [],
      language: [],
    },
    "Jarvis Testing": {
      flow: ["survey"],
      language: ["Hindi"],
      telephonyData: {
        "loanAccountDetails.emiAmount": "75252",
        "loanAccountDetails.emiDueDate": "28-03-2022",
        "email.primary": "qewreeds@gmail.com",
        callId: "62e26e45bfc1f519ab81a3ea",
        "primaryInfo.agentname": "Pragati",
        bargingCall: "True",
      },
    },
    "Kreditbee Debt": {
      flow: ["0", "dpd_minus_1", "dpd_minus_2", "due_date", "pre_emi_S_lcb"],
      language: ["English", "Hindi", "Kannada", "Telugu"],
    },
    Wheelseye: {
      flow: ["Dpd_6+", "Pre Due"],
      language: ["Hindi"],
    },
    Fincare: {
      flow: [],
      language: [],
    },
    "XYZ Telecom": {
      flow: [],
      language: [],
    },
    "test-flow-01": {
      flow: [],
      language: [],
    },
    Cred: {
      flow: [
        "#VALUE!",
        "Post Bounce DPD 1-7",
        "Post Bounce DPD 1-7_X",
        "Post Bounce DPD 8-20",
        "Post Bounce DPD 8-20_X",
      ],
      language: ["English", "Hindi"],
    },
    S_Testing: {
      flow: [],
      language: [],
    },
    "Homefirst Testing": {
      flow: [],
      language: [],
    },
    "Gamut Analytics Private Limited": {
      flow: [],
      language: [],
    },
    "Manya Testing": {
      flow: [],
      language: [],
    },
    NayakHealthcare: {
      flow: [],
      language: [],
    },
    testfor01: {
      flow: [],
      language: [],
    },
    "Kreditbee Debt Testing": {
      flow: [
        "Pre Due",
        "due_date",
        "dpd_minus_1",
        "dpd_minus_2",
        "ptp_sdf_form",
      ],
      language: ["Kannada", "Hindi", "Malayalam", "English", "Tamil", "Telugu"],
    },
    "one-sec-acc": {
      flow: [],
      language: [],
    },
    "Avail Testing": {
      flow: [
        "Due Date Reminder",
        "Post Bounce DPD 1-7",
        "Post Bounce DPD 16-30",
        "Post Bounce DPD 8-15",
        "Pre Due Reminder",
      ],
      language: ["English", "Hindi", "Kannada", "Tamil", "Telugu"],
    },
    "Capri Global": {
      flow: [
        "post_due_0_7",
        "pre due reminder",
        "pre_emi_S_h_g",
        "pre_emi_S_lca",
        "pre_emi_S_lcb",
        "pre_emi_X_h_g",
        "pre_emi_X_lca",
        "pre_emi_X_lcb",
      ],
      language: ["Gujarati", "Hindi", "Tamil"],
    },
    "AU Finance": {
      flow: [],
      language: ["English"],
    },
    test1234567: {
      flow: [],
      language: [],
    },
    LnT: {
      flow: [],
      language: [],
    },
    "Aadhar housing Testing": {
      flow: [],
      language: [],
    },
    "Bajaj Finserv": {
      flow: [
        "nil_pos",
        "post_due_0_7",
        "dpd_1_4_executive",
        "dpd_1_4_touchfree",
      ],
      language: ["English", "Hindi", "Malayalam", "Marathi", "Tamil"],
      telephonyData: {
        "contactInfo.primary": "8884974479",
        "loanAccountDetails.emiAmount": "5089",
        "loanAccountDetails.emiDueDate": "10-09-2022",
        "primaryInfo.firstName": "Kundan",
        "primaryInfo.flow": "nil_pos",
        "primaryInfo.language": "english",
        callId: "123455",
        bargingCall: "True",
        "loanAccountDetails.loanId": "12334",
        percentage_1: "5",
        percentage_2: "10",
      },
    },
    LendingKart: {
      flow: ["post_due_0_7"],
      language: ["English"],
    },
    abhiChunkTest: {
      flow: [],
      language: [],
    },
    TestTele: {
      flow: [],
      language: [],
    },
    "saarthi.ai ": {
      flow: [],
      language: [],
    },
    "First Account Testing": {
      flow: [],
      language: [],
    },
    "Mannapuram Personal Loans Testing": {
      flow: ["pre_emi_default", "pre_emi_regular"],
      language: [
        "English",
        "Hindi",
        "Kannada",
        "Malayalam",
        "Tamil",
        "Telugu",
        "Marathi",
        "Gujarati",
        "Bengali",
      ],
      telephonyData: {
        "contactInfo.primary": "8884974479",
        "loanAccountDetails.emiAmount": "9000",
        "loanAccountDetails.emiDueDate": "17-09-2022",
        "primaryInfo.firstName": "Kundan",
        "primaryInfo.flow": "pre_emi_regular",
        "primaryInfo.language": "english",
        "loanAccountDetails.noOfLoans": "2",
        clientName: "Mannapuram Personal Loans Testing",
        callId: "123455",
        "loanAccountDetails.loanId": "23045278",
        agent_name: "Mira",
      },
    },
    default: {
      flow: [
        "Pre-Due",
        "post-due",
        "post_due_0_7",
        "pre-due",
        "pre-flow",
        "pre_emi",
      ],
      language: ["Hindi", "English"],
    },
  };
  let finalResult = config[userName] ? config[userName] : config["default"];
  return finalResult;
};
