export default {
  SET_LOGGEDIN_USER_INFO: "SET_LOGGEDIN_USER_INFO",
  SET_PAGE_TYPE: "SET_PAGE_TYPE",
  SET_ACTIVE_PAGE_TYPE: "SET_ACTIVE_PAGE_TYPE",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  SET_SCHEMA_UPDATE_REQUEST: "SET_SCHEMA_UPDATE_REQUEST",
  SET_SCHEMA_UPDATE_SUCCESS: "SET_SCHEMA_UPDATE_SUCCESS",
  SET_SCHEMA_UPDATE_FAILURE: "SET_SCHEMA_UPDATE_FAILURE",
  USER_LOGOUT: "USER_LOGOUT",
  SET_REQUEST_FEATURE_API_REQUEST:"SET_REQUEST_FEATURE_API_REQUEST",
  SET_REQUEST_FEATURE_SUCCESS:"SET_REQUEST_FEATURE_SUCCESS",
  SET_REQUEST_FEATURE_FAILURE:"SET_REQUEST_FEATURE_FAILURE"
};

